### ISSUE TITLE
Redirection of errors is not going to the log file

### ISSUE THREAD

**Issue by aashish24** [CDAT/VisTrails#32]

**Comment by aashish24** [comment]
@doutriaux1 can you post the exact error message.

**Comment by aashish24** [comment]
Only happens in Mac 10.10

**Comment by doutriaux1** [comment]
10.10 error message is:

```
2015-03-30 10:14:08.773 system_profiler[44354:1072722] platformPluginDictionary: Can't get X86PlatformPlugin, return value 0
2015-03-30 10:14:08.776 system_profiler[44354:1072722] platformPluginDictionary: Can't get X86PlatformPlugin, return value 0
```

**Comment by remram44** [comment]
Redirection at the Python level (`sys.stderr`) won't affect what native (e.g. C) code does. This doesn't look like it's coming from Python.

**Comment by remram44** [comment]
Might relate to UV-CDAT/uvcdat#520 (linked for my reference)

**Comment by doutriaux1** [comment]
indeed it it coming from system-profiler on mac. maybe we try to redirect this process within vistrails
at: https://github.com/UV-CDAT/VisTrails/blob/uvcdat-master/vistrails/core/system/osx.py

**Comment by hgohil2805** [comment]
@remram44 This thing is probably coming out of these files on Mac. os_spec.rb  and macosx_spec.rb.

I dont have mac so I cant really search for it

**Comment by hgohil2805** [comment]
https://github.com/puppetlabs/facter/pull/808/files

This thing might help

**Comment by remram44** [comment]
> @remram44 This thing is probably coming out of these files on Mac. os_spec.rb and macosx_spec.rb.

Where do you see these Ruby files?

> https://github.com/puppetlabs/facter/pull/808/files

Python has its own way to redirect (`stderr` kwarg).

**Comment by hgohil2805** [comment]
Well, they are not mac files? Oops.

**Comment by vvpalav** [comment]
@doutriaux1 @williams13 @aashish24 .. can you guys test this as per your expectations?
branch added is: log-osxprofiler-errors with issue #35

**Comment by remram44** [comment]
I'm closing this so we can remove the UV-CDAT/VisTrails issue tracker (use [UV-CDAT/uvcdat/issues](https://github.com/UV-CDAT/uvcdat/issues); this one got enabled by mistake)

I don't think we want to go in and hack a redirection of non-Python messages, let me know if I'm wrong.
